modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Teams/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbteams"
version = "${version}"
displayName = "FTB Teams"
authors = "LatvianModder"
description = '''
FTB Teams adds ability to create your own teams that can be used for quests etc.
'''

[[dependencies.ftbteams]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteams]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteams]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.52,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteams]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1801.3.5-build.98,)"
ordering = "AFTER"
side = "CLIENT"
