modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/FTBTeam/FTB-Teams/issues"

[[mods]]
modId="ftbteams"
version="${file.jarVersion}"
displayName="FTB Teams"
authors="LatvianModder"
description='''
FTB Teams adds ability to create your own teams that can be used for quests etc.
'''

[[dependencies.ftbteams]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbteams]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbteams]]
    modId="ftbguilibrary"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="CLIENT"
