modLoader = "javafml"
loaderVersion = "[${neoforgeloaderversion},)"
issueTrackerURL = "https://go.ftb.team/support-mod-issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbteams"
version = "${version}"
displayName = "FTB Teams"
authors = "FTB Team"
description = '''
FTB Teams adds ability to create your own teams that can be used for quests etc.
'''

[[dependencies.ftbteams]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforgeversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteams]]
modId = "minecraft"
mandatory = true
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbteams]]
modId = "architectury"
mandatory = true
versionRange = "[${archversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbteams]]
modId = "ftblibrary"
mandatory = true
versionRange = "[${ftblibraryversion},)"
ordering = "AFTER"
side = "BOTH"
